export const socMediaComments = [
  {
    id: 1,
    postId: 201,
    name: "AliKhan",
    email: "ali.khan@mail.kz",
    body: "Очень понравился пост, жду ещё такие разборы!",
  },
  {
    id: 2,
    postId: 201,
    name: "Dana",
    email: "dana@gmail.com",
    body: "Спасибо за полезную информацию.",
  },
  {
    id: 3,
    postId: 201,
    name: "Arman",
    email: "arman@yahoo.com",
    body: "Интересно, но можно было подробнее.",
  },
  {
    id: 4,
    postId: 202,
    name: "Aruzhan",
    email: "aruzhan@mail.kz",
    body: "Очень понятно объяснил, лайк!",
  },
  {
    id: 5,
    postId: 202,
    name: "Dias",
    email: "dias@gmail.com",
    body: "Жду продолжения темы.",
  },
  {
    id: 6,
    postId: 202,
    name: "Nursultan",
    email: "nursultan@mail.kz",
    body: "Сохранил себе, пригодится.",
  },
  {
    id: 7,
    postId: 203,
    name: "Madina",
    email: "madina@gmail.com",
    body: "Полезно для новичков.",
  },
  {
    id: 8,
    postId: 203,
    name: "Ruslan",
    email: "ruslan@mail.kz",
    body: "Спасибо, стало понятнее.",
  },
  {
    id: 9,
    postId: 203,
    name: "Azamat",
    email: "azamat@gmail.com",
    body: "Хороший материал.",
  },
  {
    id: 10,
    postId: 204,
    name: "Aigerim",
    email: "aigerim@mail.kz",
    body: "Очень информативно!",
  },
];